config/routes.rb
Rails.application.routes.draw do
  resources :clocks
  resources :schools

  resources :settings

  get 'home/index' => 'home#index'
  get 'home/flot' => 'home#flot'
  get 'home/morris' => 'home#morris'
  get 'home/tables' => 'home#tables'
  get 'home/forms' => 'home#forms'

  get 'home/panels_wells' => 'home#panels_wells'
  get 'home/buttons' => 'home#buttons'
  get 'home/notifications' => 'home#notifications'
  get 'home/typography' => 'home#typography'
  get 'home/grid' => 'home#grid'
  get 'home/blank' => 'home#blank'
  get 'home/login' => 'home#login'

  root 'schools#new'

end

app/models/clock.rb
#encoding: UTF-8
class Clock < ActiveRecord::Base
  validates_presence_of  :action
  validates_presence_of  :date
  validates_presence_of  :time
  validates_presence_of  :ip
  validates_presence_of  :user

  attr_accessor :pin

  validate :check_time_and_status
  validate :check_ip
  validates_length_of :message, minimum: 10, allow_nil: true, allow_blank: true, message: "Verificare la motivazione (troppo corta)"

  def check_ip
    last_check_in=Clock.where(date: self.date, ip: self.ip).first
    if last_check_in.nil?
      return true
    elsif last_check_in.user == self.user
      return true
    elsif  message.blank?
      self.errors.add(:base, "Questo indirizzo IP risulta già utilizzato da #{last_check_in.user}. E' necessario specificare una motivazione")
      return false
    end
  end

  def  check_time_and_status
    last_check_in=Clock.where(user: self.user, date: self.date, action: "check_in").first
    last_check_out=Clock.where(user: self.user, date: self.date, action: "check_out").first
    if action=="check_in" && last_check_in
      self.errors.add(:base, "L'utente ha gia effettuato il check in alle #{last_check_in.time}")
      return false
    end
    if action=="check_out" && last_check_out
      self.errors.add(:base, "L'utente ha gia effettuato il check out alle #{last_check_out.time}")
      return false
    end

    if Setting.where(group: "user_name",key: self.pin, value: self.user).first.nil?
      self.errors.add(:base, "il pin non è corretto")
      return false
    end

    delta = (Time.now - self.time).to_i / 60
    if delta.abs > 6 && message.blank?
      self.errors.add(:base, "Differenza #{delta} minuti - Per differenze maggiori di 5 minuti è necessario indicare una motivazione")
      return false
    end

  end

  def to_s
    "#{self.user} ha effettuato #{self.action} alle ore #{self.time.to_s} - Note: #{self.message}"
  end
end

app/controllers/clocks_controller.rb
class ClocksController < ApplicationController
  before_action :set_clock, only: [:show, :edit, :update, :destroy]
  before_filter :check_administrative_ip, except: [:new, :create]
  # GET /clocks
  # GET /clocks.json
  def index

    @clocks = Clock.all
  end

  # GET /clocks/1
  # GET /clocks/1.json
  def show
    redirect_to new_clock_url
  end

  # GET /clocks/new
  def new
    @preset_ip=Setting.where(group: "ips", key: request.remote_ip).first
    @moment=Time.now.at_beginning_of_minute
    if @preset_ip.nil?
      @clock = Clock.new()
    else
      @clock = Clock.new(user: @preset_ip.value)
     end
  end

  # GET /clocks/1/edit
  #def edit
  #end

  # POST /clocks
  # POST /clocks.json
  def create
    clock_params[:message].strip!
    @clock = Clock.new(clock_params)
    @clock.date=Date.today
    # @clock.time=Time.parse("#{params[:date][:hour]}:#{params[:date][:minute]}:00", @clock.date)
    @clock.ip=request.remote_ip
    @clock.pin=params[:pin]
    @moment=@clock.time.localtime # Time.now.at_beginning_of_minute
    #@moment=@moment.advance(minutes: -(@moment.min % 5))
    respond_to do |format|
      if @clock.save
        AdminMailer.timesheet(Date.today).deliver
        format.html { redirect_to new_clock_url, notice: "Registrazione #{@clock.action} per #{@clock.user} alle #{@clock.time} avvenuta con successo." }
        format.json { render :show, status: :created, location: @clock }
      else
        format.html { render :new }
        format.json { render json: @clock.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clocks/1
  # PATCH/PUT /clocks/1.json
  def update

    respond_to do |format|
      if @clock.update(clock_params)
        format.html { redirect_to @clock, notice: 'Clock was successfully updated.' }
        format.json { render :show, status: :ok, location: @clock }
      else
        format.html { render :edit }
        format.json { render json: @clock.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clocks/1
  # DELETE /clocks/1.json
  def destroy
    @clock.destroy
    respond_to do |format|
      format.html { redirect_to clocks_url, notice: 'Clock was successfully destroyed.' }
      format.json { head :no_content }
    end
    return
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_clock
      @clock = Clock.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def clock_params
      params.require(:clock).permit(:date, :time, :user, :ip, :action, :message)
    end


end

app/helpers/clocks_helper.rb
module ClocksHelper
end

app/views/clocks/_form.html.haml
= form_for @clock , role: "form" do |f|
  - if @clock.errors.any?
    .row.well-sm
      %span.col-xs-12
        #error_explanation
          - @clock.errors.full_messages.each do |msg|
            %h3.bg-danger.well-sm= msg
  .row.well-sm
    %span.col-xs-2
      =f.select :user, options_for_select(users_for_options, @clock.user) ,{include_blank: true}, class: "form-control block"
  .row.well-sm
    %span.col-xs-2
      =password_field_tag :pin, "", class: "form-control block" , placeholder:"insert pin here"
      -#=f.text_field :ip
      =f.hidden_field :action, id: "op"
  .row.well-sm
    %span.col-xs-2.col-md-2
      =select_hour(@moment,{ start_hour: 7, end_hour: 24}, {class: "btn btn-lg btn-default btn-block"})
    %span.col-xs-2.col-md-2
      =select_minute(@moment, {minute_step: 1}, {class: "btn btn-lg btn-default btn-block"})

    -#%span.col-xs-2
      -#%button.btn.btn-xs.btn-default.btn-block{:type => "button"} +
      -#%button.btn.btn-xs.btn-default.btn-block{:type => "button"} -
  .row.well-sm
    %span.col-xs-2
      %button.btn.btn-lg.btn-success.btn-block{id: "create", :type => "button"} Create
    %span.col-xs-2
      %button.btn.btn-lg.btn-danger.btn-block{id: "delete",:type => "button"} Delete
  .row.well-sm
    %span.col-xs-12
      %label.col-xs-2.control-label Comment
      = f.text_area :message, class: "form-control block",  :rows => "3"
-if flash[:notice]
  %h3.bg-success.well-sm= flash[:notice]


:javascript
    $(document).ready( function() {
      $('#create').click(function()
        {$("#op").val("check_in");
        $("#new_clock").submit();})
      $('#delete').click(function()
          {$("#op").val("check_out");
          $("#new_clock").submit();})
    } );

app/views/clocks/edit.html.haml
%h1 Editing clock

= render 'form'

= link_to 'Show', @clock
\|
= link_to 'Back', clocks_path

app/views/clocks/index.html.haml
%h1 Listing clocks

%table.table.table-striped
  %tr
    %th Created
    %th Date
    %th Time
    %th User
    %th Ip
    %th Action
    %th Message
    %th
    %th
    %th

  - @clocks.each do |clock|
    %tr
      %td= clock.created_at.localtime
      %td= clock.date
      %td= clock.time.localtime
      %td= clock.user
      %td= clock.ip
      %td= clock.action
      %td= clock.message
      %td= link_to 'Destroy', clock, :method => :delete, :data => { :confirm => 'Are you sure?' }

app/views/clocks/new.html.haml
= render 'form'

app/views/clocks/show.html.haml
%p#notice= notice

%p
  %b Date:
  = @clock.date
%p
  %b Time:
  = @clock.time
%p
  %b User:
  = @clock.user
%p
  %b Ip:
  = @clock.ip
%p
  %b Action:
  = @clock.action
%p
  %b Message:
  = @clock.message

= link_to 'Edit', edit_clock_path(@clock)
\|
= link_to 'Back', clocks_path